### ISSUE TITLE
Objects in query strings

### ISSUE THREAD

**Issue by jonathancwein** [jdegre/5GC_APIs#19]
In TS29503_Nudm_SDM.yaml, line 55, PlmnId is an object, not a string. Should all query parameters be strings? A PlmnIdStr type that concatenates MCC and MNC would be simple and would not require a standard serialization method to generate the query string. The use of an Object in a query string breaks tools like Swagger viewer.

Maybe line 55 should change from:

 $ref: 'TS29571_CommonData.yaml#/components/schemas/PlmnId'

to:

 $ref: 'TS29571_CommonData.yaml#/components/schemas/PlmnIdStr'  

where PlmnIdStr is a new string type, the concatenation of MCC + MNC?

Then the query parameter is plmn-id=mccmnc

Otherwise, there has to be some standard way to serialize Objects into query string elements, e.g.,

{plmn-id: [{mcc: 'xxx'}, {mnc: 'yyy'}]

**Comment by jdegre** [comment]
hi,
sorry for the slow reply, i overlooked this issue since it must have come during a 3GPP meeting, where we had a really busy week :)

i agree that maybe for this specific case of PLMN ID as query parameter, it would've been much easier to use a normalized string, which is quite straightforward.

in any case, just let me point out that sending JSON objects as query parameters is actually defined in the API spec you point out (TS29503_Nudm_SDM.yaml). Check lines 52-53, where we used the construct:

```
content:
  application/json:
```

inside the definition of the query parameter itself. This, according to the OpenAPI spec, has a well-defined semantics, similar to what you wrote at the end of your post (maybe not the prettiest for a query string, but well...).

**Comment by jonathancwein** [comment]
Thank you. Checked the OpenAPI spec. Got it. Yes, serialize as application/json
