### ISSUE TITLE
TS32291_Nchf_ConvergedCharging.yaml and TS29122_ChargeableParty.yaml fail to pass SOAPUI pro validation

### ISSUE THREAD

**Issue by migmurillo** [jdegre/5GC_APIs#20]
Hello,

I'm not sure if it is an issue on API or SOAPUI but I would like to comment that when I tried to import these yamls with ReadyAPI 2.8.2 fail with this error:

while scanning for the next token found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation) in 'string', line 301, column 17: items: ^

After sometime troubleshooting the issue is with the items "array type" as following:
 < #        flowInfo: 
 < #          type: array
 < #          items:
 < #            $ref: 'TS29122_CommonData.yaml#/components/schemas/FlowInfo'
 < #          minItems: 1
 < #          description: Describes the application flows.

Please anybody has the same issue? What is the best tool to use swagger 5GC?

Thanks 
Best Regards,
Miguel

**Comment by gatopeich** [comment]
I had the same issue with Ruamel.yaml.
Those tabs hanging at line end are not legal in YAML.
Just delete them.

**Comment by migmurillo** [comment]
Thanks,
I can't found any tab on this file. I have added this to .vimrc to find them but I can't see any tab.

highlight SpecialKey ctermfg=1
set list
set listchars=tab:T>

Best Regards,
Miguel

**Comment by jdegre** [comment]
There are a few TAB chars around, in the YAML files, agreed.

I'll try to get rid of all of them asap in this repo, since they break the syntax checks of some tools, as you have noticed, and I'll try to correct them as well in the master source of the YAML files (the MS Word files of the 3GPP Technical Specifications), although this will take more time.

Often, the offending TAB is not found in the YAML file that you are parsing, but in one of the YAML files externally referenced through $refs.

The YAML files you have mentioned in the title do not contain any TAB, but there is one at least in:
- TS29512_Npcf_SMPolicyControl.yaml
- TS29525_Npcf_UEPolicyControl.yaml
